services:
  patcher:
    env_file: ".env"
    restart: "no"
    image: patch-updater:${PATCH_VERSION}
    build:
      context: ./docker
      args:
        GIT_TOKEN: ${GIT_TOKEN}
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      PATCH_VERSION: ${PATCH_VERSION}
      BRANCH: ${BRANCH}